# Docker Compose file for testing
version: "2"
services:

  web_test:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.test
    depends_on:
      - mbs_db_test

  mbs_db_test:
    image: metabrainz/musicbrainz-test-database:master
